version: "3.3"
services:
  api:
    image: somanykings/reyes:1.0
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: secretpw
      MYSQL_DATABASE: prod
      REDIS_HOST: redis
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: topsecretpw
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: secretpw
      MYSQL_DATABASE: prod
  redis:
    image: redis:alpine
